# -*- coding: utf-8 -*-
"""sentiment_analysis_functions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IjIuRIFUxTOaqq3HFn3RZmxKEwKdMX83
"""

#Import modules
import pandas as pd
import numpy as np
import datasets
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
import wandb


#Create separate column for an individual emotion
def pre_process_for_multilabel(data):

  #Turn individual string of emotions into list and create a series of lists
  multiple_empathies = data["empathy"].apply(lambda x: x.split(","))

  #Clear white space to standardize labels
  multiple_empathies = multiple_empathies.apply(lambda x: [a.strip() for a in x])

  #Create new dataframe with each indivudal emotion in 1 column
  multiple_empathies_df = pd.DataFrame(multiple_empathies.to_list())

  #Replace na
  multiple_empathies_df.fillna("",inplace=True)
  multiple_empathies_df.index = multiple_empathies.index
  multiple_empathies_df = multiple_empathies_df.rename(columns = {0:"empathy", 1: "empathy_1", 2: "empathy_2", 3: "empathy_3", 4:"empathy_4"})

  #merge new df with original df
  data = data.merge(multiple_empathies_df, how = "left", left_index = True, right_index = True)
  data.drop(["empathy_x"], axis = 1, inplace = True)
  data = data.rename(columns = {"empathy_y": "empathy_0"})

  # columns = ["empathy_0", "empathy_1", "empathy_2", "empathy_3", "empathy_4"]
  # for column in columns:
  #   data[column] = data[column].apply(lambda x: x.strip())

  return data, multiple_empathies

#Set polarity for emotions without an original value since no polarity was assigned to examples with multiple emotions
def find_polarity_for_pos_neg_neutral(data, empathies_dict):

  data["polarity_0"] = data["empathy_0"].map(empathies_dict)
  data["polarity_1"] = data["empathy_1"].iloc[np.where(data["empathy_1"] != "")]\
  .replace(empathies_dict.keys(), empathies_dict.values())
  data["polarity_2"] = data["empathy_2"].iloc[np.where(data["empathy_2"] != "")]\
  .replace(empathies_dict.keys(), empathies_dict.values())
  data["polarity_3"] = data["empathy_3"].iloc[np.where(data["empathy_3"] != "")]\
  .replace(empathies_dict.keys(), empathies_dict.values())
  data["polarity_4"] = data["empathy_4"].iloc[np.where(data["empathy_4"] != "")]\
  .replace(empathies_dict.keys(), empathies_dict.values())

  return data

#Find average value of polarity for examples with multiple emotions
def average_polarity(data):
    polarity_cols = ["polarity_0", "polarity_1", "polarity_2", "polarity_3", "polarity_4"]
    # force every polarity column to numeric; anything non-numeric becomes NaN (ignored by mean)
    for col in polarity_cols:
        data[col] = pd.to_numeric(data[col], errors="coerce")
    data["average_polarity_score"] = data[polarity_cols].mean(axis=1)
    return data

#Set base emotion (positive, negative, or neutral) for examples with multiple emotions
def set_base_emotion(data):

  mapping = {"negative":0, "neutral":1, "positive":2}
  data["labels_base_emotions"] = data["polarity"].map(mapping)
  return data


#Create one hot encoding for labels for multilabel
def one_hot_encode(data, multiple_empathies):

  one_hot = MultiLabelBinarizer()
  multiple_empathies_one_hot_encoded = (one_hot.fit_transform(multiple_empathies))
  data["labels_all_emotions_one_hot_encoded"] = pd.Series(list(multiple_empathies_one_hot_encoded))

  labels = one_hot.classes_
  id2label = {idx:label for idx, label in enumerate(labels)}
  label2id = {label:idx for idx, label in enumerate(labels)}

  return data, id2label, label2id


def remove_examples_with_outliers(data):

  data.drop([495, 3544], axis =0, inplace = True)
  data.reset_index(inplace = True)
  data.drop(["index"], axis = 1, inplace = True)
  return data


def conditions(x):
  if   x > 0:   return "positive"
  elif x < 0:   return "negative"
  else:           return "neutral"

#Finding emotions in messages dataset that aren't listed in the empathies dictionary
def find_emotions_with_no_polarity(data):
  list_of_emotions_with_no_polarity = []
  for col, series in data[["polarity_0", "polarity_1", "polarity_2", "polarity_3",\
                           "polarity_4"]].items(): # iterating over all columns
    list_of_emotions_with_no_polarity += [(s,series.name) for s in series.unique()\
                                          if isinstance(s, str)]
  return list_of_emotions_with_no_polarity

#Setting polarity for emotions without any originally listed polarity
def set_polarity_for_unlisted_emotions(data, list_of_emotions_with_no_polarity, empathies_dict):
    # For each emotion that had no polarity mapping, set its polarity column to 1.0 (treated as positive)
    for polarity_value, polarity_column in list_of_emotions_with_no_polarity:
        # rows in this column equal to the unlisted polarity value
        mask = data[polarity_column] == polarity_value
        data.loc[mask, polarity_column] = 1.0

    # Any empathy_0 with no mapping in empathies_dict → set polarity_0 to 1.0
    unmapped_mask = data["empathy_0"].map(empathies_dict).isna()
    data.loc[unmapped_mask, "polarity_0"] = 1.0

    return data


def pre_process(data, empathies):

  #Set Series type to string
  data['empathy'] = data['empathy'].astype('str')
  data["message"] = data["message"].astype('str')

  #Remove outliers
  data.iloc[2137, data.columns.get_loc("empathy")] = 'scared,anxious,angry'
  data = remove_examples_with_outliers(data)

  #Drop unnecessary columns
  data.drop(["num_seen", "ignore"], axis = 1, inplace = True)
  data.drop_duplicates(inplace = True, ignore_index = True)

  #Setting polarity for emotions for base emotion (pos,neg,neu) modeling
  empathies_dict = dict(zip(empathies.empathy, empathies.polarity))
  data["polarity_score"] = data["empathy"].map(empathies_dict)


  (data, multiple_empathies) = pre_process_for_multilabel(data)
  data = find_polarity_for_pos_neg_neutral(data, empathies_dict)



  data = average_polarity(data)
  data["polarity_score"] = data["polarity_score"].fillna(data["average_polarity_score"])

  func = np.vectorize(conditions)
  polarity = func(data["polarity_score"])
  data["polarity"] = polarity
  data = set_base_emotion(data)

  list_of_emotions_with_no_polarity = find_emotions_with_no_polarity(data)
  data = set_polarity_for_unlisted_emotions(data, list_of_emotions_with_no_polarity, empathies_dict)

  data, id2label, label2id = one_hot_encode(data, multiple_empathies)

  return data, id2label, label2id


def create_dataset_dict(data):

  label_counts = data["labels_all_emotions_one_hot_encoded"].astype(str).value_counts()
  one_freq = label_counts[label_counts==1].keys()
  one_freq_idxs = sorted(list(data[data["labels_all_emotions_one_hot_encoded"].astype(str).isin(one_freq)].index), reverse=True)

  one_freq_for_all_messages = [data["message"].pop(i) for i in one_freq_idxs]
  one_freq_for_all_messages = pd.Series(one_freq_for_all_messages).set_axis(one_freq_idxs)

  one_freq_for_all_labels = [data["labels_all_emotions_one_hot_encoded"].pop(i) for i in one_freq_idxs]
  one_freq_for_all_labels = pd.Series(one_freq_for_all_labels).set_axis(one_freq_idxs)

  data.drop(one_freq_idxs, axis=0, inplace=True)

  X = data["message"]
  y = data["labels_all_emotions_one_hot_encoded"]

  X_train, X_test, y_train, y_test = train_test_split(
          X, y, test_size=0.2, stratify=list(data["labels_all_emotions_one_hot_encoded"].values)
          )

  label_counts = y_train.astype(str).value_counts()
  one_freq = label_counts[label_counts==1].keys()
  one_freq_idxs = sorted(list(y_train[y_train.astype(str).isin(one_freq)].index), reverse=True)

  one_freq_for_train_messages = [X_train.pop(i) for i in one_freq_idxs]
  one_freq_for_train_messages = pd.Series(one_freq_for_train_messages).set_axis(one_freq_idxs)

  one_freq_for_train_labels = [y_train.pop(i) for i in one_freq_idxs]
  one_freq_for_train_labels = pd.Series(one_freq_for_train_labels).set_axis(one_freq_idxs)

  X_train, X_validation, y_train, y_validation = train_test_split(
          X_train, y_train, test_size=0.25, stratify = list(y_train.values)
          )

  # Add one frequency data to train data
  X_train = pd.concat([X_train, one_freq_for_train_messages, one_freq_for_all_messages])
  y_train = pd.concat([y_train, one_freq_for_train_labels, one_freq_for_all_labels])


  train_df = pd.DataFrame({'text': X_train,
                          'labels': y_train
                        })

  validation_df = pd.DataFrame({'text': X_validation,
                              'labels': y_validation
                        })

  test_df = pd.DataFrame({'text': X_test,
                        'labels': y_test
                      })

  train_dataset = datasets.Dataset.from_dict(train_df)
  validation_dataset = datasets.Dataset.from_dict(validation_df)
  test_dataset = datasets.Dataset.from_dict(test_df)

  messages = datasets.DatasetDict({"train":train_dataset, "validation":validation_dataset,\
                                   "test":test_dataset})

  return messages


def create_sweep_id():

  # method
  sweep_config = {
      'method': 'random',
      "metric": {"name": "precision", "goal": "maximize", "target": 0.9},
      'program': 'train.py',
      "early_terminate": {"type": "hyperband", "min_iter": 2}
  }


  # hyperparameters
  parameters_dict = {
      'model_ckpt': {
          'values': ["bert-base-uncased", "roberta-base", "albert-base-v2", "xlnet-base-cased"]

      },
      'epochs': {
          'min': 3,
          'max': 8
          },
      'batch_size': {
          'values': [8, 16, 32]
          },
      'lr': {
          'distribution': 'log_uniform_values',
          'min': 1e-7,
          'max': 1e-3
      },
      'weight_decay': {
          'min': 0.0,
          'max': 1.0
      },
      'warmup_steps': {
          'min':0,
          "max":80
      },
      'optim':{
          'values': ["adamw_torch", "adafactor", "sgd", "adagrad"]
      },
      'early_stopping': {
          'values': [True]
      }
  }

  sweep_config['parameters'] = parameters_dict

  sweep_id = wandb.sweep(sweep_config, project='woebot_sentiment_analysis')

  return sweep_id

